### ISSUE TITLE
Where can you read about the available actions?

### ISSUE THREAD

**Issue by Gyga8K** [p0o/steem-bot#13]
I'm trying to create a library like this but for the Go language, but I can not find the documentation that tells me what parameters to pass to the API to perform actions such as writing a post or a comment.

**Comment by p0o** [comment]
You mean writing a wrapper of Go on top of this library? Why not considering a direct connection to the Steem blockchain?

**Comment by Gyga8K** [comment]
I want to connect directly to the blockchain but I do not find enough documentation.

**Comment by p0o** [comment]
This issue is not related to this project. You could have found the necessary documentation on the internet:

https://steemit.github.io/steemit-docs/#
