### ISSUE TITLE
How can i get users all old and new comments 

### ISSUE THREAD

**Issue by tomriddle54** [p0o/steem-bot#17]
Hello i want to get user old and new comments how can i get it someone here knows about it

**Comment by TwinkieWInkie** [comment]
SteemSQL > SELECT * FROM [Comments] WHERE [title] != '' AND [username] = 'cunt' ORDER BY created DESC;

What's with the people with disabilities that keep posting issues where there are none?
If you need help being a scriptkiddie, there's chat channels and forums for that...

**Comment by TwinkieWInkie** [comment]
@p0o Can be closed, not related(as usual)
