### ISSUE TITLE
Proposal to Draft a Privacy Policy and About Us page for Steembot

### ISSUE THREAD

**Issue by Pope19** [p0o/steem-bot#19]
Greetings,

I am a copywriter, and have contributed to many App and Platforms using my writing skills.

A privacy policy is a document that states an App/site potential collection/use of visitors /users data.
About us normally found on the landing page gives a brief description of the App. 

I am willing to contribute to the development and stability of your platform through documentation some of which will provide you with legal indemnity.

Your response is anticipated.

Thank you.

@pope1995 on steemit
@pope1995#6757 on discord

**Comment by p0o** [comment]
This is a JS package not a app or website. You better do more research about your potential customers if you want to stay in the business.
