### ISSUE TITLE
SyntaxError: Identifier 'SteemBot' has already been declared

### ISSUE THREAD

**Issue by cloh76** [p0o/steem-bot#2]
I used your randowhale example code and when i execute the bot using the **node .** command I get the following error.  Can you point me in the right direction?

const SteemBot = require('../dist/loader').default;
      ^

SyntaxError: Identifier 'SteemBot' has already been declared
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:605:28)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3

**Comment by p0o** [comment]
You are not supposed to use that way of require in your code. You should use the npm package. I clearly described it in the comments of `randowhale` project. See:

```javascript
// change the line below to include the library from npm package:
// const SteemBot = require('steem-bot').default
// or:
// import SteemBot from 'steem-bot';
const SteemBot = require('../dist/loader').default;
```
follow the instruction to install the npm package (explained in the first page of repository) and try again.

**Comment by cloh76** [comment]
I downloaded and installed the npm package using: npm install steem-bot --save

Do i create an index.js and use the following code?

const SteemBot = require('randowhale.js').default
const targetUsers = ['poloniex', 'bittrex'];

const bot = new SteemBot({**username**, **postingKey**, **activeKey**}); **Replacing the BOLD items with my info**

bot.onDeposit(targetUsers, (data) => {
  console.log(data); // { from: 'p0o', to: 'poloniex', amount: '10 STEEM', memo: 'GbH4HgV35Ygv'}
});

bot.start();

and then updating the randowhale.js file with my information?  

Sorry I am trying to learn coding

**Comment by p0o** [comment]
Yes install the npm packages and make your own `js` files to work with
