### ISSUE TITLE
Change target variable while the bot is running

### ISSUE THREAD

**Issue by phaitonican** [p0o/steem-bot#21]
Hello p0o,
I really appreciate you work.
I have a database, where I update the targets. However, do I have the problem to update the targetUsers variable in for example the .onPost() function while the bot is already running.
You maybe got an Idea? Thanks!

**Comment by p0o** [comment]
Hi @phaitonican , thank you very much.

I believe you can do it by handling that part yourself. Something like this:

```javascript
let targetUsers = ['p0o' 'ned'];
bot.onComment(handleComment);

function handleComment(data, responder) {
  // change it on the fly or appoint to a function which synchronously returns the latest changes
  targetUsers = ['p0o'];
  
  // exit if author is not in targetUsers
  if(!targetUsers.includes(data.author)) return;

  console.log('user %s commented!', data.author);
  console.log(data.body);

  responder.comment('Hi there! I just upvoted you using SteemBot JavaScript library!');
  responder.upvote(); // 100% upvote

}
```

Let me know if it fixes your problem so I can close this issue.

**Comment by phaitonican** [comment]
oh i made it work with it, thank you. So it refreshes the variable every time someone comments. Tricky workaround thank you!
