### ISSUE TITLE
Delegate function

### ISSUE THREAD

**Issue by phaitonican** [p0o/steem-bot#23]
Hi again,

I needed the delegate function in my bot, I was asking if I could try to implement it by myself, but I had no idea how to start and need to work me in a little, since im pretty newbie.
So I see the .onComment etc.. functions, guess I need to start there somehwere. Using the steem js library...
So thanks if you can help out otherwise I close this!

**Comment by p0o** [comment]
You can always use steemjs in combination with steem-bot. Use their `delegateVestingShares()` function to do the job. Here is the [doc](https://github.com/steemit/steem-js/tree/master/doc)

I close the issue now, if you had any problem with that function you can open an issue in steemjs.

**Comment by phaitonican** [comment]
hey thanks i couldnt make it clear. i need to see if someone delegates to me, like an onDelegate function and onUndelegate or something like that.

**Comment by p0o** [comment]
I see, I added the feature-request label here and re-open it until someone implement it or I do later. But I don't have enough time to work on this project for some time. If you need it you may try to do it yourself. Wouldn't be that hard if you can understand the current codebase.
