### ISSUE TITLE
Error: Something went wrong with streamOperations method of Steem-js

### ISSUE THREAD

**Issue by FreddyFish** [p0o/steem-bot#8]
So i have been trying to create something using steem-bot. It's working fine, but crashing randomly probably when checking for new deposits, and this is what i'm getting.

1|index    | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
1|index    | Error: Something went wrong with streamOperations method of Steem-js
1|index    |     at /root/steemBot/node_modules/steem-bot/dist/core.js:116:17
1|index    |     at /root/steemBot/node_modules/steem/lib/api/index.js:374:21
1|index    |     at /root/steemBot/node_modules/steem/lib/api/index.js:347:21
1|index    |     at /root/steemBot/node_modules/steem/lib/api/index.js:320:21
1|index    |     at /root/steemBot/node_modules/steem/lib/api/index.js:291:21
1|index    |     at tryCatcher (/root/steemBot/node_modules/bluebird/js/release/util.js:16:23)
1|index    |     at Promise._settlePromiseFromHandler (/root/steemBot/node_modules/bluebird/js/release/promise.js:512:31)
1|index    |     at Promise._settlePromise (/root/steemBot/node_modules/bluebird/js/release/promise.js:569:18)
1|index    |     at Promise._settlePromise0 (/root/steemBot/node_modules/bluebird/js/release/promise.js:614:10)
1|index    |     at Promise._settlePromises (/root/steemBot/node_modules/bluebird/js/release/promise.js:689:18)
1|index    |     at Async._drainQueue (/root/steemBot/node_modules/bluebird/js/release/async.js:133:16)
1|index    |     at Async._drainQueues (/root/steemBot/node_modules/bluebird/js/release/async.js:143:10)
1|index    |     at Immediate.Async.drainQueues (/root/steemBot/node_modules/bluebird/js/release/async.js:17:14)
1|index    |     at runCallback (timers.js:800:20)
1|index    |     at tryOnImmediate (timers.js:762:5)
1|index    |     at processImmediate [as _immediateCallback] (timers.js:733:5)

**Comment by ghost** [comment]
This is the RPC node failing, 
The reason for this is because steem-bot uses a streaming service to the RPC node that then tells you if there's a new transaction. If the stream is disconnected for any reason (RPC node failing), then you'll see that error and the bot will crash.

**Comment by FreddyFish** [comment]
Can i use another node that's more stable?
Or can i prevent node from crashing when the stream is disconnected?

**Comment by ghost** [comment]
Best solution is to setup RPC node redundancy.
Have a separate process that constantly checks the list of RPC nodes to see if they go down.
Check list here: http://geo.steem.pl/

Preventing crash is not easy, best solution to prevent crash entirely is to reprogram the bot and use accounthistory() to get transaction list rather than a streaming service.

**Comment by Slapbox** [comment]
Any idea why it's only started recently? Seems to be only since they discontinued `steemd.steemit.com`

**Comment by p0o** [comment]
Sorry for late response. I think it's much easier to solve this with proper error handling and adding methods to SteemBot to easily change nodes. Nothing is wrong with using `streamOperations` if we can handle the node's hiccup and reset the connection properly. I will try to add something soon to fix this issue.

**Comment by FreddyFish** [comment]
@p0o  - Awesome! That would be much appreciated. I'm looking forward to that.

**Comment by wonsama** [comment]
@p0o Awesome ! I'm looking forward to that. too

**Comment by p0o** [comment]
Please install the new package <0.8.0> and let me know if the problem is fixed or not. You also can use the new two examples in the `/example` directory as well for error handling and changing the RPC node.

**Comment by wonsama** [comment]
ok i got it thank you

2018. 3. 12. 20:05에 "Pooria" <notifications@github.com>님이 작성:

**Comment by p0o** [comment]
I think we are done here. Let me know in a new issue if this error continue to show up.
